[package]
name = "chapter-2"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
luminance = "0.38"
luminance-derive = "0.5"
luminance-glfw = "0.12"
